# XDG Base Directories
export XDG_STATE_HOME="${HOME}"/.local/state
export XDG_DATA_HOME="${HOME}"/.local/share
export XDG_CONFIG_HOME="${HOME}"/.config
export XDG_CACHE_HOME="${HOME}"/.cache

# ZSH paths
export ZDOTDIR="${XDG_CONFIG_HOME}"/zsh
export ZPLUGINDIR="${XDG_DATA_HOME}"/zsh/plugins

# Declutter home directory
export LESSHISTFILE="${XDG_STATE_HOME}"/less/history
export XINITRC="${XDG_CONFIG_HOME}"/X11/xinitrc
export GNUPGHOME="${XDG_DATA_HOME}"/gnupg
export GOPATH="${XDG_DATA_HOME}"/go
export PYENV_ROOT="${XDG_DATA_HOME}"/pyenv
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}"/npm/npmrc
export NODE_REPL_HISTORY="${XDG_DATA_HOME}"/node/node_repl_history
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}"/npm/config
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}"/npm
export NPM_CONFIG_PREFIX="${XDG_DATA_HOME}"/npm
export PYTHONSTARTUP="${XDG_CONFIG_HOME}"/python/startup.py
export WGETRC="${XDG_CONFIG_HOME}"/wget/wgetrc
export DOCKER_CONFIG="${XDG_CONFIG_HOME}"/docker
export WINEPREFIX="${XDG_DATA_HOME}"/wine/default
export WINEDLLOVERRIDES=winemenubuilder.exe=d
export NVM_DIR="${XDG_DATA_HOME}"/nvm
export W3M_DIR="${XDG_STATE_HOME}"/w3m
export VAGRANT_HOME="${XDG_DATA_HOME}"/vagrant
export VAGRANT_ALIAS_FILE="${XDG_DATA_HOME}"/vagrant/aliases

# Opt out of telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Virtualization defaults
export VAGRANT_DEFAULT_PROVIDER=libvirt
export LIBVIRT_DEFAULT_URI=qemu:///system

# Program defaults
export EDITOR=nvim
export SUDOEDITOR=nvim
export PAGER=most

# User path envvar
typeset -U path PATH
path=(
    "${HOME}"/bin
    "${HOME}"/.local/bin
    "${HOME}"/.cargo/bin
    "${XDG_DATA_HOME}"/npm/bin
    "${XDG_DATA_HOME}"/go/bin
    "${XDG_DATA_HOME}"/JetBrains/Toolbox/scripts
    $path
); export PATH
