# xdg base directory specification
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_LIB_HOME="$HOME/.local/lib"

# zsh config directory
export ZDOTDIR=$HOME/.config/zsh

# declutter home directory
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node/node_repl_history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/startup.py"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export WINEPREFIX="$XDG_DATA_HOME/wine/default"
export WINEDLLOVERRIDES=winemenubuilder.exe=d
export NVM_DIR="$XDG_DATA_HOME/nvm"

# opt out of telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# default apps
export EDITOR="nvim"
export SUDOEDITOR="nvim"
export PAGER="most"

# path
typeset -U path PATH
path=(
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    "$HOME/.local/share/npm/bin"
    "$HOME/.local/share/go/bin"
    "$HOME/.local/share/JetBrains/Toolbox/scripts"
    $path
); export PATH
